config/routes.rb
Picuploader::Application.routes.draw do
  devise_for :users

  resources :pics
  
  root :to => "pics#index"

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  
  has_attached_file :pic, :styles => { :thumb => "400x400>"},
 
  :storage => :s3,
  :bucket => '5my-pics',
  :s3_credentials => {
     :access_key_id => 'ID',
      :secret_access_key => 'ID'
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
    before_filter :authenticate_user!
  
  # GET /pics
  # GET /pics.xml
  def index
    @pics = Pic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pics }
    end
  end

  # GET /pics/1
  # GET /pics/1.xml
  def show
    @pic = Pic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pic }
    end
  end

  # GET /pics/new
  # GET /pics/new.xml
  def new
    @pic = Pic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pic }
    end
  end

  # GET /pics/1/edit
  def edit
    @pic = Pic.find(params[:id])
  end

  # POST /pics
  # POST /pics.xml
  def create
    @pic = Pic.new(params[:pic])

    respond_to do |format|
      if @pic.save
        format.html { redirect_to(@pic, :notice => 'Pic was successfully created.') }
        format.xml  { render :xml => @pic, :status => :created, :location => @pic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pics/1
  # PUT /pics/1.xml
  def update
    @pic = Pic.find(params[:id])

    respond_to do |format|
      if @pic.update_attributes(params[:pic])
        format.html { redirect_to(@pic, :notice => 'Pic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.xml
  def destroy
    @pic = Pic.find(params[:id])
    @pic.destroy

    respond_to do |format|
      format.html { redirect_to(pics_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picuploader</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
		<div id="user_nav">
			<% if user_signed_in? %>
			Signed in as <%= current_user.email %>. Not you?
			<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
			<% else %>
			<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
			<% end %>
		</div>
<%= yield %>

</body>
</html>

app/views/pics/_form.html.erb
<%= form_for @pic, :html => { :multipart => true} do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.file_field :pic %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<h1>Westlake 2011 - Homecoming Pics</h1>

<%= link_to 'New Pic', new_pic_path %> <br> <hr>

<% @pics.each do |pic| %>
  <%= link_to (image_tag pic.pic.url(:thumb)), pic  %> <br>

    <%= link_to 'Original Size', pic %> | <%= link_to 'Delete Pic', pic, :confirm => 'Are you sure?', :method => :delete %> <br>
<br>
  
<% end %>

<br />

app/views/pics/new.html.erb
<h1>New pic</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Go back to the list', pics_path %> <br>
<H3> To download the pic, just right click the image and click "Save image as..." </h3>

<p>
<%= image_tag @pic.pic.url() %>
</p>